
version: '3.9'
services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - /Users/vedashruta/Workspace/mongodb-docker:/data/db
  netflix-go:
    build: .
    ports:
      - "9800:9800"
    depends_on:
      - mongo_db